// <auto-generated />
using System;
using DataAccess.Context.IdentityContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Context.IdentityContext.Migrations
{
    [DbContext(typeof(AppIdentityDbContext))]
    partial class AppIdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.UserEntites.Concrete.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d56b0610-7157-4fca-b989-bfdabac1f4f5"),
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 981, DateTimeKind.Local).AddTicks(9497),
                            Name = "admin",
                            NormalizedName = "ADMIN",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fb230ada-67a9-40f3-96b2-c9c602ed7fee"),
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 981, DateTimeKind.Local).AddTicks(9547),
                            Name = "customerManager",
                            NormalizedName = "CUSTOMERMANAGER",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7131d431-27c8-4b46-b7db-305cdbac3bef"),
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 981, DateTimeKind.Local).AddTicks(9551),
                            Name = "teacher",
                            NormalizedName = "TEACHER",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("499a3674-2aae-469a-8940-41893b636c00"),
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 981, DateTimeKind.Local).AddTicks(9554),
                            Name = "student",
                            NormalizedName = "STUDENT",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.UserEntites.Concrete.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstPassword")
                        .HasColumnType("text");

                    b.Property<bool>("HasPasswordChanged")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2b28166-5def-49e5-bb0b-741a16f886d4"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "fde5fd50-da3e-4f0a-87ec-5796c07d85c7",
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 163, DateTimeKind.Local).AddTicks(5004),
                            Email = "admin@edu.com",
                            EmailConfirmed = false,
                            FirstName = "Administrator",
                            HasPasswordChanged = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EDU.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEITLwwtPtwwfl0uC16DHYYy+Vp8JKRd7sdaJo+JGDWdFwKNXUanfkFNQ5x8WyEotVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1aadb8f8-6448-44b2-95bb-971d80a931f4",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("89db9ff5-9f40-4c5e-a17d-1c1ec45636c0"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1985, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "3601f791-9308-4e4e-a656-943da35402b2",
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 298, DateTimeKind.Local).AddTicks(9535),
                            Email = "ahmet.cekic@edu.com",
                            EmailConfirmed = false,
                            FirstName = "Ahmet",
                            HasPasswordChanged = true,
                            LastName = "Çekiç",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMET.CEKIC@EDU.COM",
                            NormalizedUserName = "AHMET.CEKIC",
                            PasswordHash = "AQAAAAIAAYagAAAAELwO9RnZk2bPSpT4HwdHBv4uzwif2cMJllpR7YRqLjrJKCnJ0gdLSKqiYqZclw1UTg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "334c13fe-b117-439b-a53a-b75f184b7f38",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "ahmet.cekic"
                        },
                        new
                        {
                            Id = new Guid("976e4111-519f-485f-a21b-186e30f07371"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1996, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "2892d002-0b21-4f94-9c77-bfd243c11cd6",
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 448, DateTimeKind.Local).AddTicks(9860),
                            Email = "sinaemre.bekar@edu.com",
                            EmailConfirmed = false,
                            FirstName = "Sina Emre",
                            HasPasswordChanged = true,
                            LastName = "Bekar",
                            LockoutEnabled = false,
                            NormalizedEmail = "SINAEMRE.BEKAR@EDU.COM",
                            NormalizedUserName = "SINAEMRE.BEKAR",
                            PasswordHash = "AQAAAAIAAYagAAAAEPGeZcYwHpk9FliIX/2ZIEDlcq1FDmW+IwhvA7NPInNCwX/dkDMOtBo3C/VN5gec0A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aaf70b06-a9d8-440f-a552-deb552d0309c",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "sinaemre.bekar"
                        },
                        new
                        {
                            Id = new Guid("d3a95b67-ce52-4c1d-835a-14df01e3501f"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ab6b678f-aa3b-4756-817f-5e6791fa8cd1",
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 579, DateTimeKind.Local).AddTicks(879),
                            Email = "murat.yeler@edu.com",
                            EmailConfirmed = false,
                            FirstName = "Murat",
                            HasPasswordChanged = true,
                            LastName = "Yeler",
                            LockoutEnabled = false,
                            NormalizedEmail = "MURAT.YELER@EDU.COM",
                            NormalizedUserName = "MURAT.YELER",
                            PasswordHash = "AQAAAAIAAYagAAAAEMUhWwrb6/etMfFRGncuTaPCJ3T1DAJnaeclcR9G+k5+iVMZr/9xR6uQBk/nbcupJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a4032c8-8ff9-4001-b93c-b9f2ddb36ada",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "murat.yeler"
                        },
                        new
                        {
                            Id = new Guid("43c10399-6734-42d1-91c5-838b551a066e"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2014, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "b937d670-0c29-4dea-b43d-3e10cf8a278a",
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 693, DateTimeKind.Local).AddTicks(7050),
                            Email = "miray.cekic@edu.com",
                            EmailConfirmed = false,
                            FirstName = "Miray",
                            HasPasswordChanged = true,
                            LastName = "Çekiç",
                            LockoutEnabled = false,
                            NormalizedEmail = "MIRAY.CEKIC@EDU.COM",
                            NormalizedUserName = "MIRAY.CEKIC",
                            PasswordHash = "AQAAAAIAAYagAAAAENUOP6J0Hr09z6zuOAJIAtfLMVqu8AQc+IYpF13SFWe0HBsoFOC3tDLnLkmp0A66rw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "53c91a29-08f4-4a56-a84d-c1c3caac7ccf",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "miray.cekic"
                        },
                        new
                        {
                            Id = new Guid("8b12fe04-e7d8-4fe6-ba17-1283ac7abaa9"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1975, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "dbe240d6-317f-4daa-ba81-e29e57a7037d",
                            CreatedDate = new DateTime(2025, 4, 4, 1, 38, 49, 831, DateTimeKind.Local).AddTicks(1078),
                            Email = "danilo.zanna@edu.com",
                            EmailConfirmed = false,
                            FirstName = "Danilo",
                            HasPasswordChanged = true,
                            LastName = "Zanna",
                            LockoutEnabled = false,
                            NormalizedEmail = "DANILO.ZANNA@EDU.COM",
                            NormalizedUserName = "DANILO.ZANNA",
                            PasswordHash = "AQAAAAIAAYagAAAAEKRXUYy32DAoJb/oadZIJ3emF98qCQbRmB+VyI0KSGFgOdrS8tj7zhqRz7plyEU17A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7a9f06d9-a621-487f-9682-21a4bb1b5153",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "danilo.zanna"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c2b28166-5def-49e5-bb0b-741a16f886d4"),
                            RoleId = new Guid("d56b0610-7157-4fca-b989-bfdabac1f4f5")
                        },
                        new
                        {
                            UserId = new Guid("89db9ff5-9f40-4c5e-a17d-1c1ec45636c0"),
                            RoleId = new Guid("fb230ada-67a9-40f3-96b2-c9c602ed7fee")
                        },
                        new
                        {
                            UserId = new Guid("976e4111-519f-485f-a21b-186e30f07371"),
                            RoleId = new Guid("7131d431-27c8-4b46-b7db-305cdbac3bef")
                        },
                        new
                        {
                            UserId = new Guid("d3a95b67-ce52-4c1d-835a-14df01e3501f"),
                            RoleId = new Guid("499a3674-2aae-469a-8940-41893b636c00")
                        },
                        new
                        {
                            UserId = new Guid("43c10399-6734-42d1-91c5-838b551a066e"),
                            RoleId = new Guid("499a3674-2aae-469a-8940-41893b636c00")
                        },
                        new
                        {
                            UserId = new Guid("8b12fe04-e7d8-4fe6-ba17-1283ac7abaa9"),
                            RoleId = new Guid("499a3674-2aae-469a-8940-41893b636c00")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ApplicationCore.UserEntites.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
